baseURL = 'https://rvramesh20.github.io/myblog'
languageCode = 'en-us'
title = "Ramesh>Blog"
theme = "hugo-paper-mod"

[params]
  disableHLJS = false                         # don't use highlight.js
  twitter = 'rvramesh20'                # twitter.com/YOUR_TWITTER_ID
  github = 'rvramesh20'                  # github.com/YOUR_GITHUB_ID
  linkedin = '/in/ramesh-rv-b2b57a8'


[menu]


  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 20

